IF OBJECT_ID('TW_PC_CRONO_CIERRE_NOMINA') IS NOT NULL
   DROP PROCEDURE TW_PC_CRONO_CIERRE_NOMINA;  
GO 

	CREATE PROCEDURE TW_PC_CRONO_CIERRE_NOMINA
/********************OBJETIVO: GENERA EL CRONOGRAMA DE CIERRE DE CIERRE DE NOVEDADES DE NOMINA*******************************
       
************************************  DECLARACION DE VARIABLE  ************************************************************ */



   -- EL PARAMETRO AÑO SE DEJA QUEMADO POR QUE LA BASE DE DATOS ESTA MUY DESACTUALIZADA Y NO TRAE DATOS DEL AÑO ACTUAL
   AS

		BEGIN
				SET LANGUAGE SPANISH;
				SELECT DATENAME(MONTH,fec_cie) AS MES,
					DATENAME(WEEKDAY,CONVERT(DATETIME,fec_cie,105))  AS DIA,
					DAY (FEC_CIE) AS CIERRE,
					DATENAME(WEEKDAY,CONVERT(DATETIME,fec_pag,105)) AS DIA_CIERRE,
					DAY(FEC_PAG) AS PAGO
					FROM CIERRE_NOVPAG
					WHERE ANO = '2013'
					ORDER BY COD_PER ASC;

		END;	


		EXEC TW_PC_CRONO_CIERRE_NOMINA;